import type { TripSummaryDto } from '@tripick/types';

import { PLANNER_TRIP_MOCK } from './main-planner.mock';

export const TRIP_SUMMARIES_MOCK: TripSummaryDto[] = [
  {
    id: PLANNER_TRIP_MOCK.id,
    title: PLANNER_TRIP_MOCK.title,
    destination: '경주',
    startDate: PLANNER_TRIP_MOCK.meta.startDate,
    endDate: PLANNER_TRIP_MOCK.meta.endDate,
    durationLabel: PLANNER_TRIP_MOCK.meta.durationLabel,
    status: 'upcoming',
    statusLabel: '곧 출발',
    members: PLANNER_TRIP_MOCK.members,
    coverEmoji: '🏛️',
    highlight: '황리단길 카페·불국사 위주 1박 2일',
    itemCount: PLANNER_TRIP_MOCK.items.length,
    hasDetail: true,
  },
  {
    id: 'demo-busan-2n3d',
    title: '부산 2박 3일 감도 여행',
    destination: '부산',
    startDate: '2026-06-03',
    endDate: '2026-06-05',
    durationLabel: '2박 3일 · 6/3 수 ~ 6/5 금',
    status: 'draft',
    statusLabel: '초안',
    members: [
      { id: 'm1', initial: '태', color: '#3182F6' },
      { id: 'm2', initial: '박', color: '#6B7684' },
    ],
    coverEmoji: '🌊',
    highlight: '광안리·해운대·전포 카페거리',
    itemCount: 6,
    hasDetail: false,
  },
  {
    id: 'demo-jeju-3n4d',
    title: '제주 3박 4일 워케이션',
    destination: '제주',
    startDate: '2026-04-12',
    endDate: '2026-04-15',
    durationLabel: '3박 4일 · 4/12 일 ~ 4/15 수',
    status: 'done',
    statusLabel: '다녀옴',
    members: [
      { id: 'm1', initial: '태', color: '#3182F6' },
      { id: 'm2', initial: '박', color: '#6B7684' },
      { id: 'm3', initial: '홍', color: '#191F28' },
      { id: 'm4', initial: '민', color: '#00A86B' },
    ],
    coverEmoji: '🌴',
    highlight: '동쪽 해안 + 한라산 트래킹',
    itemCount: 12,
    hasDetail: false,
  },
  {
    id: 'demo-gangneung-day',
    title: '강릉 당일치기',
    destination: '강릉',
    startDate: '2026-07-20',
    endDate: '2026-07-20',
    durationLabel: '당일치기 · 7/20 월',
    status: 'draft',
    statusLabel: '초안',
    members: [{ id: 'm1', initial: '태', color: '#3182F6' }],
    coverEmoji: '☕',
    highlight: '안목해변 카페 + 회 한 끼',
    itemCount: 3,
    hasDetail: false,
  },
];
